project_id = "cnswwlpsjdhgtmzofvzy"

[functions.chatbot]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.generate-paper]
verify_jwt = false

[functions.optimize-algorithm]
verify_jwt = false
